#
# Continuous Integration (CI) script for execution on every event that changes the main branch.
#
name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'npm'

      - name: Install dependencies
          run: npm ci

      - name: Build application
          run: npm run build

      - name: Run tests
          run: npm test
